apiVersion: v1
kind: Service
metadata:
  name: backendservice1
  labels:
    app: backendservice1
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: backend-pod
