apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeployment1
  labels:
    app: backenddeployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod

  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-pod

    spec:
      containers:
        - name: backend-container
          image: gcr.io/absolute-realm-353309/myapp:v2.0
          ports:
            - containerPort: 5000
