
apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontenddeployment1
  labels:
    app: frontenddeployment1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod

  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod

    spec:
      containers:
        - name: frontend-container
          image: gcr.io/absolute-realm-353309/myapp:v1.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx
              mountPath: "/etc/nginx/nginx.conf"
              subPath: "nginx.conf"
      volumes:
      - name: nginx
        configMap:
          name: configmap
